### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by wimstefan** [B4mbus/oxocarbon-lua.nvim#3]
Thanks for this exciting new colorscheme!
Would it be possible to add an option to make the background transparent?

**Comment by Dich0tomy** [comment]
@wimstefan Hey. With the new change you should be able to do
```lua
vim.g.oxocarbon_lua_transparent = true
```
or
```vim
let g:oxocarbon_lua_transparent = 1
```
To enable transparency. Let me know if it works!

**Comment by wimstefan** [comment]
Thank you so much for the lightning fast response @B4mbus !
It looks wonderful so far. The only thing visually disturbing a bit is that folds and {fold,number,sign}columns are still not transparent. Not sure if that is easy to solve but it would make the appearance a bit more consistent if they have a transparent background as well ...

**Comment by Dich0tomy** [comment]
@wimstefan that would be nice, indeed. I don't really have time to look into that now, I'll see what I can do tommorow. Thanks for instant feedback!

**Comment by Dich0tomy** [comment]
@wimstefan Hey. Does it work now with the new update?

**Comment by wimstefan** [comment]
Hello @B4mbus :)
Looking good so far 👍
To make the transparent look complete you could even consider to include the line numbers as well ...

```patch
diff --git a/lua/oxocarbon-lua/init.lua b/lua/oxocarbon-lua/init.lua
index ed8c949..d0216c8 100644
--- a/lua/oxocarbon-lua/init.lua
+++ b/lua/oxocarbon-lua/init.lua
@@ -13,7 +13,7 @@ local get_colors = function()
  end

  local set_terminal_colors = function(colors)
-   if vim.g.oxocarbon_lua_keep_terminal then
+   if vim.g.oxocarbon_lua_keep_terminal then
        return
    end

@@ -85,10 +85,10 @@ return {
      highlight('Cursor', 1, 5)
      highlight('CursorLine', 18, 2)
      highlight('CursorColumn', 18, 2)
-    highlight('CursorLineNr', 5, 18)
+    highlight('CursorLineNr', 5, conditional_bg(18))
      highlight('QuickFixLine', 18, 2)
      highlight('Error', 5, 12)
-    highlight('LineNr', 4, 1)
+    highlight('LineNr', 4, conditional_bg(1))
      highlight('NonText', 3, conditional_bg(18))
      highlight('Normal', 5, conditional_bg(1))
      highlight('Pmenu', 5, 2)
```

**Comment by Dich0tomy** [comment]
@wimstefan thanks for feedback! I don't have a way to set my background to transparent right now so I don't know which options would make it look right. I am also not really experienced in making themes, as this is just a port of somebody else's theme to lua. 

How does it look with the new update?

**Comment by wimstefan** [comment]
Hey @B4mbus :)
I've tested the patch before sending it to you and to my eyes it looks quite clean & consistent now. 
![scrot-2022-08-12-13:13](https://user-images.githubusercontent.com/4605934/184342998-dc15b5e4-8e65-4756-b5ff-a3c8079601f0.png)

I guess it's up to others how they like it ... ;)
I want to thank you anyway for the fast and kind support you're offering 🙏

**Comment by Dich0tomy** [comment]
@wimstefan Awesome! Thank you very much for your feedback! By the way, what font are you using and can we close this issue after that?

**Comment by wimstefan** [comment]
At the moment I use my own customization of Iosevka font ...
Another favourite of mijn is Recursive Casual. 

And yes the issue can be closed as resolved.

Thanks a lot for all your efforts! 🙏🏼
