### ISSUE TITLE
Fix telescope support

### ISSUE THREAD

**Issue by ysomad** [B4mbus/oxocarbon-lua.nvim#4]
Is it just me or telescope with oxocarbon looks kinda bad?

**Comment by Dich0tomy** [comment]
@ysomad what kind of changes do you expect? Generally the original colorscheme seems lacking a lot of things and seems like it's made specifically for the author, I'm thinking of rewriting it and making it more complete and configurable, tho that's some work and I don't really have that much time everyday.

**Comment by ysomad** [comment]
> @ysomad what kind of changes do you expect? Generally the original colorscheme seems lacking a lot of things and seems like it's made specifically for the author, I'm thinking of rewriting it and making it more complete and configurable, tho that's some work and I don't really have that much time everyday.

Seems like it's lacking borders in telescope windows and some colors looks odd atleast it looks like it for me.

How it looks in oxocarbon
![image](https://user-images.githubusercontent.com/49870662/184912608-dea6ed1c-874c-4b49-91b1-50bc01a171a9.png)

Gruvbox for example
![image](https://user-images.githubusercontent.com/49870662/184912794-5c3dc3c5-a476-4043-90e3-8afa0e122d30.png)

**Comment by Dich0tomy** [comment]
@ysomad I see. I'll look into how telescope higlight groups work today night or tommorow.

**Comment by Dich0tomy** [comment]
@ysomad Hey. With the new changes you are able to do
```lua
vim.g.oxocarbon_lua_alternative_telescope = true
```
To change the telescope's theming. 

Try it and tell me how it feels! Cheers.

**Comment by ysomad** [comment]
> @ysomad Hey. With the new changes you are able to do
> 
> ```lua
> vim.g.oxocarbon_lua_alternative_telescope = true
> ```
> 
> To change the telescope's theming.
> 
> Try it and tell me how it feels! Cheers.

I set global variable you've provided and updated plugin but it does not work :(
Telescope still the same even with true option.
![image](https://user-images.githubusercontent.com/49870662/185803887-fb79aa6d-43e6-4f1b-93df-fab60ce0d6b1.png)

**Comment by Dich0tomy** [comment]
@ysomad  are you sure you updated the plugin?
Also, I'm pretty sure the option should be set before the plugin loads.

**Comment by ysomad** [comment]
> @ysomad are you sure you updated the plugin? Also, I'm pretty sure the option should be set before the plugin loads.

Yes, I updated with `PackerSync` and options.lua module is loading before plugins in my configuration
![image](https://user-images.githubusercontent.com/49870662/185803989-9e41acb7-fe19-4d19-87d3-4f4e31e805ac.png)

**Comment by ysomad** [comment]
> @ysomad are you sure you updated the plugin? Also, I'm pretty sure the option should be set before the plugin loads.

I got it, if I set the variable before setting colorscheme it works!

**Comment by ysomad** [comment]
I love it! Thank you so much! I think you can close the issue.

**Comment by Dich0tomy** [comment]
@ysomad awesome, no problem.
